# Generated by Django 5.2.10 on 2026-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faq_remove_user_is_admin_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.JSONField(),
        ),
    ]
